development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: yarrble_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: yarrble_production
